development:
  adapter: postgresql
  host: localhost
  database: training_db
  username: demo-username
  password: demo-pass

production:
  adapter: postgresql
  host: db.internal.training
  database: production_demo
  username: demo
  password: demo
